name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          show-progress: false
      - run: dotnet build
      - run: dotnet test --no-build UnitTests/UnitTests.csproj
